apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springbootapp
  namespace: springbootapp
spec:
  replicas: 3
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: springbootapp
        serviceName: springbootapp-service
    spec:
      containers:
      - name: springboot-rest
        image: wiku/springboot-rest:latest
        ports:
          - containerPort: 9090
        resources:
            limits:
              memory: 100Mi
              cpu: 200m
            requests:
              memory: 100Mi
              cpu: 200m